### ISSUE TITLE
Listenbrainz not scrobbling

### ISSUE THREAD

**Issue by benjaminbhollon** [vjeranc/cmus-status-scrobbler#7]
## Environment
Python version: 3.10.9
cmus version: v2.10.0

## Log file

```

57239 2023-04-08 17:00:35 ERROR root Error happened
Traceback (most recent call last):
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 468, in <module>
    main()
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 455, in main
    status = parse_cmus_status_line(rest)
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 251, in parse_cmus_status_line
    return Status(**r)
TypeError: Status.__new__() missing 4 required positional arguments: 'status', 'file', 'title', and 'duration'
57252 2023-04-08 17:00:46 ERROR root Error happened
Traceback (most recent call last):
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 468, in <module>
    main()
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 455, in main
    status = parse_cmus_status_line(rest)
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 251, in parse_cmus_status_line
    return Status(**r)
TypeError: Status.__new__() missing 3 required positional arguments: 'file', 'title', and 'duration'
57261 2023-04-08 17:00:47 ERROR root Error happened
Traceback (most recent call last):
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 468, in <module>
    main()
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 455, in main
    status = parse_cmus_status_line(rest)
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 251, in parse_cmus_status_line
    return Status(**r)
TypeError: Status.__new__() missing 3 required positional arguments: 'file', 'title', and 'duration'
57265 2023-04-08 17:00:49 INFO root Status(status='playing', file='/home/benjamin/music/Aaron Copland/Greatest Hits/01 Fanfare for the Common Man.flac', artist='Aaron Copland', albumartist='Aaron Copland', album='Greatest Hits', discnumber='1', tracknumber='1', title='Fanfare for the Common Man', date='1991-09-06', duration='212', musicbrainz_trackid='7e400cd2-1aee-46bb-b4c1-a1138a316e42', cur_time=datetime.datetime(2023, 4, 8, 22, 0, 49, 352552))
57277 2023-04-08 17:00:50 INFO root Status(status='playing', file='/home/benjamin/music/Aaron Copland/Greatest Hits/02 Appalachian Spring.flac', artist='Aaron Copland', albumartist='Aaron Copland', album='Greatest Hits', discnumber='1', tracknumber='2', title='Appalachian Spring', date='1991-09-06', duration='1526', musicbrainz_trackid='f71d7054-f95e-49fa-804c-b8b5062a3307', cur_time=datetime.datetime(2023, 4, 8, 22, 0, 50, 893508))
57300 2023-04-08 17:00:56 ERROR root Error happened
Traceback (most recent call last):
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 468, in <module>
    main()
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 455, in main
    status = parse_cmus_status_line(rest)
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 251, in parse_cmus_status_line
    return Status(**r)
TypeError: Status.__new__() missing 3 required positional arguments: 'file', 'title', and 'duration'
57316 2023-04-08 17:01:15 ERROR root Error happened
Traceback (most recent call last):
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 468, in <module>
    main()
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 455, in main
    status = parse_cmus_status_line(rest)
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 251, in parse_cmus_status_line
    return Status(**r)
TypeError: Status.__new__() missing 3 required positional arguments: 'file', 'title', and 'duration'
57529 2023-04-08 17:02:46 ERROR root Error happened
Traceback (most recent call last):
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 468, in <module>
    main()
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 455, in main
    status = parse_cmus_status_line(rest)
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 251, in parse_cmus_status_line
    return Status(**r)
TypeError: Status.__new__() missing 4 required positional arguments: 'status', 'file', 'title', and 'duration'
57538 2023-04-08 17:02:51 ERROR root Error happened
Traceback (most recent call last):
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 468, in <module>
    main()
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 455, in main
    status = parse_cmus_status_line(rest)
  File "/home/benjamin/.bin/cmus_status_scrobbler.py", line 251, in parse_cmus_status_line
    return Status(**r)
TypeError: Status.__new__() missing 4 required positional arguments: 'status', 'file', 'title', and 'duration'


```

**Comment by vjeranc** [comment]
It looks like the tags that are sent to the script miss the `status`, `file, `title` and `duration` of the track. This is unlikely.

Could you show me how you pass the `cmus` arguments to the program?

Basically, there's a line:
```python
 args, rest = parser.parse_known_args()
```
that captures, first, your modifications of the program, and then the rest of the arguments it does not recognize (which are the cmus status arguments).

```python
    status = parse_cmus_status_line(rest)
```

This line fails because it fails to provide all of the arguments necessary for the status. Which means it's not really that Listenbrainz does not scrobble, it's more that the program that needs to scrobble isn't receiving all the data it needs to create a proper scrobble event.

**Comment by vjeranc** [comment]
Okay, then the easiest way to investigate is,
add `import sys` at the top of the program

then below `setup_loggin(args.log_path...` add
```
    logging.info(args)
    logging.info(rest)
    logging.info(sys.argv)
```

Then paste the new logs here.

**Comment by vjeranc** [comment]
```
452956 2023-04-10 19:55:59 INFO root Namespace(auth=False, ini='/home/vjeran/.config/cmus/cmus_status_scrobbler.ini', db_path='/ho
me/vjeran/.config/cmus/cmus_status_scrobbler.sqlite3', log_path='/tmp/cmus_scrobbler.log', log_db=True)
452956 2023-04-10 19:55:59 INFO root ['status', 'playing', 'file', '/home/vjeran/Music/flac/Josh Ritter/2013 - The Beast in Its Tr
acks [flac]/05 Nightmares.flac', 'artist', 'Josh Ritter', 'albumartist', 'Josh Ritter', 'album', 'The Beast in Its Tracks', 'discn
umber', '1', 'tracknumber', '5', 'title', 'Nightmares', 'date', '2013-05-13', 'musicbrainz_trackid', 'c4dce90a-044e-4a31-8c7a-db18
a696aaa1', 'duration', '219']
452956 2023-04-10 19:55:59 INFO root ['/home/vjeran/src/cmus-status-scrobbler/cmus_status_scrobbler.py', '--log-db', '--log-path',
 '/tmp/cmus_scrobbler.log', 'status', 'playing', 'file', '/home/vjeran/Music/flac/Josh Ritter/2013 - The Beast in Its Tracks [flac
]/05 Nightmares.flac', 'artist', 'Josh Ritter', 'albumartist', 'Josh Ritter', 'album', 'The Beast in Its Tracks', 'discnumber', '1
', 'tracknumber', '5', 'title', 'Nightmares', 'date', '2013-05-13', 'musicbrainz_trackid', 'c4dce90a-044e-4a31-8c7a-db18a696aaa1',
 'duration', '219']
```

This is what is printed out for my currently playing track.

**Comment by benjaminbhollon** [comment]
Okay, so funny thing, it seems to be working now. I must have set something up wrong and fixed it without realizing it? :laughing: 

I guess we can close this, but if it helps, these are the logs I got:

```
18036 2023-04-10 13:01:01 INFO root Namespace(auth=False, ini='/home/benjamin/.config/cmus/cmus_status_scrobbler.ini', db_path='/home/benjamin/.config/cmus/cmus_status_scrobbler.sqlite3', log_path=None, log_db=False)
18036 2023-04-10 13:01:01 INFO root ['status', 'playing', 'file', '/home/benjamin/music/P.D.Q. Bach/Music for an Awful Lot of Winds & Percussion/02 Grand Serenade for an Awful Lot of Winds & Percussion, S. 1000_ I. Grand Entrance.flac', 'artist', 'P.D.Q. Bach', 'albumartist', 'P.D.Q. Bach', 'album', 'Music for an Awful Lot of Winds & Percussion', 'discnumber', '1', 'tracknumber', '2', 'title', 'Grand Serenade for an Awful Lot of Winds & Percussion, S. 1000: I. Grand Entrance', 'date', '1992', 'musicbrainz_trackid', 'a79523d9-0d7f-4a59-a940-8b9ee4f8c30c', 'duration', '105']
18036 2023-04-10 13:01:01 INFO root ['/home/benjamin/.bin/cmus_status_scrobbler.py', 'status', 'playing', 'file', '/home/benjamin/music/P.D.Q. Bach/Music for an Awful Lot of Winds & Percussion/02 Grand Serenade for an Awful Lot of Winds & Percussion, S. 1000_ I. Grand Entrance.flac', 'artist', 'P.D.Q. Bach', 'albumartist', 'P.D.Q. Bach', 'album', 'Music for an Awful Lot of Winds & Percussion', 'discnumber', '1', 'tracknumber', '2', 'title', 'Grand Serenade for an Awful Lot of Winds & Percussion, S. 1000: I. Grand Entrance', 'date', '1992', 'musicbrainz_trackid', 'a79523d9-0d7f-4a59-a940-8b9ee4f8c30c', 'duration', '105']
18036 2023-04-10 13:01:01 INFO root Status(status='playing', file='/home/benjamin/music/P.D.Q. Bach/Music for an Awful Lot of Winds & Percussion/02 Grand Serenade for an Awful Lot of Winds & Percussion, S. 1000_ I. Grand Entrance.flac', artist='P.D.Q. Bach', albumartist='P.D.Q. Bach', album='Music for an Awful Lot of Winds & Percussion', discnumber='1', tracknumber='2', title='Grand Serenade for an Awful Lot of Winds & Percussion, S. 1000: I. Grand Entrance', date='1992', duration='105', musicbrainz_trackid='a79523d9-0d7f-4a59-a940-8b9ee4f8c30c', cur_time=datetime.datetime(2023, 4, 10, 18, 1, 1, 540922))
18155 2023-04-10 13:02:46 INFO root Namespace(auth=False, ini='/home/benjamin/.config/cmus/cmus_status_scrobbler.ini', db_path='/home/benjamin/.config/cmus/cmus_status_scrobbler.sqlite3', log_path=None, log_db=False)
18155 2023-04-10 13:02:46 INFO root ['status', 'playing', 'file', '/home/benjamin/music/P.D.Q. Bach/Music for an Awful Lot of Winds & Percussion/03 Grand Serenade for an Awful Lot of Winds & Percussion, S. 1000_ II. Simply Grand Minuet.flac', 'artist', 'P.D.Q. Bach', 'albumartist', 'P.D.Q. Bach', 'album', 'Music for an Awful Lot of Winds & Percussion', 'discnumber', '1', 'tracknumber', '3', 'title', 'Grand Serenade for an Awful Lot of Winds & Percussion, S. 1000: II. Simply Grand Minuet', 'date', '1992', 'musicbrainz_trackid', 'a65b9258-9f76-4852-80f0-99f5a5463fb1', 'duration', '176']
18155 2023-04-10 13:02:46 INFO root ['/home/benjamin/.bin/cmus_status_scrobbler.py', 'status', 'playing', 'file', '/home/benjamin/music/P.D.Q. Bach/Music for an Awful Lot of Winds & Percussion/03 Grand Serenade for an Awful Lot of Winds & Percussion, S. 1000_ II. Simply Grand Minuet.flac', 'artist', 'P.D.Q. Bach', 'albumartist', 'P.D.Q. Bach', 'album', 'Music for an Awful Lot of Winds & Percussion', 'discnumber', '1', 'tracknumber', '3', 'title', 'Grand Serenade for an Awful Lot of Winds & Percussion, S. 1000: II. Simply Grand Minuet', 'date', '1992', 'musicbrainz_trackid', 'a65b9258-9f76-4852-80f0-99f5a5463fb1', 'duration', '176']
18155 2023-04-10 13:02:46 INFO root Status(status='playing', file='/home/benjamin/music/P.D.Q. Bach/Music for an Awful Lot of Winds & Percussion/03 Grand Serenade for an Awful Lot of Winds & Percussion, S. 1000_ II. Simply Grand Minuet.flac', artist='P.D.Q. Bach', albumartist='P.D.Q. Bach', album='Music for an Awful Lot of Winds & Percussion', discnumber='1', tracknumber='3', title='Grand Serenade for an Awful Lot of Winds & Percussion, S. 1000: II. Simply Grand Minuet', date='1992', duration='176', musicbrainz_trackid='a65b9258-9f76-4852-80f0-99f5a5463fb1', cur_time=datetime.datetime(2023, 4, 10, 18, 2, 46, 326000))
18155 2023-04-10 13:02:46 INFO root Scrobbling previous tracks for listenbrainz
18155 2023-04-10 13:02:46 INFO root {'sk': '5caa09bd794e8bf3c6dce928d6da682e9a1f195f', 'artist[0]': 'P.D.Q. Bach', 'track[0]': 'Grand Serenade for an Awful Lot of Winds & Percussion, S. 1000: I. Grand Entrance', 'timestamp[0]': '1681149661', 'album[0]': 'Music for an Awful Lot of Winds & Percussion', 'trackNumber[0]': '2', 'mbid[0]': 'a79523d9-0d7f-4a59-a940-8b9ee4f8c30c', 'duration[0]': '105', 'api_key': '94f2d53c-15bd-42e5-bef5-d4d60c2af623', 'method': 'track.scrobble'}
18155 2023-04-10 13:02:46 INFO root <?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
  <scrobbles accepted="1" ignored="0">
    <scrobble>
      <track corrected="0">Grand Serenade for an Awful Lot of Winds &amp; Percussion, S. 1000: I. Grand Entrance</track>
      <artist corrected="0">P.D.Q. Bach</artist>
      <album corrected="0">Music for an Awful Lot of Winds &amp; Percussion</album>
      <albumArtist corrected="0">P.D.Q. Bach</albumArtist>
      <timestamp>1681149661</timestamp>
      <ignoredMessage code="0"></ignoredMessage>
    </scrobble>
  </scrobbles>
</lfm>
```

Thanks for the help. :)

**Comment by vjeranc** [comment]
Yep, the logs look good.

**Comment by benjaminbhollon** [comment]
I'm wondering if those logs were left behind from my troubleshooting before I figured out and something else that was my fault was meaning the tracks weren't scrobbling (say, if the script wasn't actually being called?).
